<template>
  <div class="app-container">
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="el-icon-plus" size="mini" @click="handleAdd">新增</el-button></el-col><right-toolbar @queryTable="getList"></right-toolbar></el-row>
    <el-table v-loading="loading" :data="chargeList" :height="tableHeight" border fit>
      <el-table-column label="患者" prop="patientName" min-width="160" show-overflow-tooltip><template slot-scope="scope">{{ scope.row.patientName || '-' }}</template></el-table-column><el-table-column label="应收" prop="totalAmount" min-width="110" /><el-table-column label="已收" prop="paidAmount" min-width="110" /><el-table-column label="状态" prop="orderStatus" min-width="100" /><el-table-column label="创建时间" prop="createTime" min-width="170"><template slot-scope="scope">{{ parseTime(scope.row.createTime) }}</template></el-table-column>
      <el-table-column label="操作" width="150"><template slot-scope="scope"><el-button type="text" size="mini" @click="handleUpdate(scope.row)">修改</el-button><el-button type="text" size="mini" @click="handleDelete(scope.row)">删除</el-button></template></el-table-column>
    </el-table>
    <pagination v-show="total > 0" :total="total" :page.sync="queryParams.pageNum" :limit.sync="queryParams.pageSize" @pagination="getList" />
    <el-dialog :title="title" :visible.sync="open" width="560px" append-to-body><el-form ref="form" :model="form" label-width="90px"><el-form-item label="患者"><el-input-number v-model="form.patientId" :min="1" /></el-form-item><el-form-item label="接诊记录"><el-input-number v-model="form.visitId" :min="0" /></el-form-item><el-form-item label="应收金额"><el-input-number v-model="form.totalAmount" :precision="2" :min="0" /></el-form-item><el-form-item label="已收金额"><el-input-number v-model="form.paidAmount" :precision="2" :min="0" /></el-form-item><el-form-item label="状态"><el-select v-model="form.orderStatus"><el-option label="待收费" value="0" /><el-option label="部分收费" value="1" /><el-option label="已收费" value="2" /><el-option label="已退款" value="3" /><el-option label="已作废" value="4" /></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" /></el-form-item></el-form><div slot="footer" class="dialog-footer"><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="open=false">取 消</el-button></div></el-dialog>
  </div>
</template>
<script>
import { listCharge, getCharge, addCharge, updateCharge, delCharge } from '@/api/medical/charge'
import medicalTableHeight from '@/views/medical/mixins/tableHeight'
export default { name: 'MedicalCharge', mixins: [medicalTableHeight], data() { return { loading: true, total: 0, chargeList: [], open: false, title: '', queryParams: { pageNum: 1, pageSize: 10 }, form: {} } }, created() { this.getList() }, methods: { getList() { this.loading = true; listCharge(this.queryParams).then(r => { this.chargeList = r.rows; this.total = r.total; this.loading = false }) }, reset() { this.form = { totalAmount: 0, paidAmount: 0, orderStatus: '0' } }, handleAdd() { this.reset(); this.title = '新增收费单'; this.open = true }, handleUpdate(row) { getCharge(row.chargeOrderId).then(r => { this.form = r.data; this.title = '修改收费单'; this.open = true }) }, submitForm() { const req = this.form.chargeOrderId ? updateCharge(this.form) : addCharge(this.form); req.then(() => { this.$modal.msgSuccess('保存成功'); this.open = false; this.getList() }) }, handleDelete(row) { this.$modal.confirm('是否确认删除收费单？').then(() => delCharge(row.chargeOrderId)).then(() => { this.getList(); this.$modal.msgSuccess('删除成功') }).catch(() => {}) } } }
</script>
