<template>
  <div class="app-container">
    <el-form :model="queryParams" ref="queryForm" size="small" :inline="true">
      <el-form-item label="材料名称"><el-input v-model="queryParams.materialName" clearable @keyup.enter.native="handleQuery" /></el-form-item>
      <el-form-item><el-button type="primary" icon="el-icon-search" size="mini" @click="handleQuery">搜索</el-button><el-button icon="el-icon-refresh" size="mini" @click="resetQuery">重置</el-button></el-form-item>
    </el-form>
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="el-icon-plus" size="mini" @click="handleAdd">新增</el-button></el-col><right-toolbar @queryTable="getList"></right-toolbar></el-row>
    <el-table v-loading="loading" :data="materialList" :height="tableHeight" border fit>
      <el-table-column label="材料名称" prop="materialName" min-width="160" /><el-table-column label="类型" prop="materialType" width="90" /><el-table-column label="单位" prop="unit" width="80" /><el-table-column label="库存" prop="stockQuantity" width="110" /><el-table-column label="安全库存" prop="safetyStock" width="110" /><el-table-column label="状态" prop="status" width="90"><template slot-scope="scope">{{ scope.row.status === '0' ? '正常' : '停用' }}</template></el-table-column>
      <el-table-column label="操作" width="150"><template slot-scope="scope"><el-button type="text" size="mini" @click="handleUpdate(scope.row)">修改</el-button><el-button type="text" size="mini" @click="handleDelete(scope.row)">删除</el-button></template></el-table-column>
    </el-table>
    <pagination v-show="total > 0" :total="total" :page.sync="queryParams.pageNum" :limit.sync="queryParams.pageSize" @pagination="getList" />
    <el-dialog :title="title" :visible.sync="open" width="560px" append-to-body><el-form ref="form" :model="form" label-width="90px"><el-form-item label="材料名称"><el-input v-model="form.materialName" /></el-form-item><el-form-item label="类型"><el-select v-model="form.materialType"><el-option label="药品" value="0" /><el-option label="耗材" value="1" /><el-option label="加工件" value="2" /><el-option label="其他" value="3" /></el-select></el-form-item><el-form-item label="单位"><el-input v-model="form.unit" /></el-form-item><el-form-item label="库存"><el-input-number v-model="form.stockQuantity" :precision="2" :min="0" /></el-form-item><el-form-item label="安全库存"><el-input-number v-model="form.safetyStock" :precision="2" :min="0" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio label="0">正常</el-radio><el-radio label="1">停用</el-radio></el-radio-group></el-form-item></el-form><div slot="footer" class="dialog-footer"><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="open=false">取 消</el-button></div></el-dialog>
  </div>
</template>
<script>
import { listMaterial, getMaterial, addMaterial, updateMaterial, delMaterial } from '@/api/medical/material'
import medicalTableHeight from '@/views/medical/mixins/tableHeight'
export default { name: 'MedicalMaterial', mixins: [medicalTableHeight], data() { return { loading: true, total: 0, materialList: [], open: false, title: '', queryParams: { pageNum: 1, pageSize: 10, materialName: undefined }, form: {} } }, created() { this.getList() }, methods: { getList() { this.loading = true; listMaterial(this.queryParams).then(r => { this.materialList = r.rows; this.total = r.total; this.loading = false }) }, handleQuery() { this.queryParams.pageNum = 1; this.getList() }, resetQuery() { this.resetForm('queryForm'); this.handleQuery() }, reset() { this.form = { materialType: '1', stockQuantity: 0, safetyStock: 0, status: '0' } }, handleAdd() { this.reset(); this.title = '新增药品耗材'; this.open = true }, handleUpdate(row) { getMaterial(row.materialId).then(r => { this.form = r.data; this.title = '修改药品耗材'; this.open = true }) }, submitForm() { const req = this.form.materialId ? updateMaterial(this.form) : addMaterial(this.form); req.then(() => { this.$modal.msgSuccess('保存成功'); this.open = false; this.getList() }) }, handleDelete(row) { this.$modal.confirm('是否确认删除"' + row.materialName + '"？').then(() => delMaterial(row.materialId)).then(() => { this.getList(); this.$modal.msgSuccess('删除成功') }).catch(() => {}) } } }
</script>
