<template>
  <div class="app-container">
    <el-row :gutter="10" class="mb8"><el-col :span="1.5"><el-button type="primary" plain icon="el-icon-plus" size="mini" @click="handleAdd">新增</el-button></el-col><right-toolbar @queryTable="getList"></right-toolbar></el-row>
    <el-table v-loading="loading" :data="followupList" :height="tableHeight" border fit>
      <el-table-column label="患者" prop="patientName" min-width="150" show-overflow-tooltip><template slot-scope="scope">{{ scope.row.patientName || '-' }}</template></el-table-column><el-table-column label="负责人" prop="ownerUserName" min-width="120" show-overflow-tooltip><template slot-scope="scope">{{ scope.row.ownerUserName || '-' }}</template></el-table-column><el-table-column label="回访时间" prop="followupTime" min-width="170"><template slot-scope="scope">{{ parseTime(scope.row.followupTime) }}</template></el-table-column><el-table-column label="类型" prop="followupType" min-width="90" /><el-table-column label="状态" prop="followupStatus" min-width="90" /><el-table-column label="结果" prop="followupResult" min-width="200" show-overflow-tooltip />
      <el-table-column label="操作" width="150"><template slot-scope="scope"><el-button type="text" size="mini" @click="handleUpdate(scope.row)">修改</el-button><el-button type="text" size="mini" @click="handleDelete(scope.row)">删除</el-button></template></el-table-column>
    </el-table>
    <pagination v-show="total > 0" :total="total" :page.sync="queryParams.pageNum" :limit.sync="queryParams.pageSize" @pagination="getList" />
    <el-dialog :title="title" :visible.sync="open" width="620px" append-to-body><el-form ref="form" :model="form" label-width="90px"><el-form-item label="患者"><el-input-number v-model="form.patientId" :min="1" /></el-form-item><el-form-item label="负责人"><el-input-number v-model="form.ownerUserId" :min="0" /></el-form-item><el-form-item label="回访时间"><el-date-picker v-model="form.followupTime" type="datetime" value-format="yyyy-MM-dd HH:mm:ss" /></el-form-item><el-form-item label="类型"><el-select v-model="form.followupType"><el-option label="复诊" value="0" /><el-option label="术后" value="1" /><el-option label="欠费" value="2" /><el-option label="其他" value="3" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="form.followupStatus"><el-option label="待回访" value="0" /><el-option label="已完成" value="1" /><el-option label="已取消" value="2" /></el-select></el-form-item><el-form-item label="结果"><el-input v-model="form.followupResult" type="textarea" /></el-form-item></el-form><div slot="footer" class="dialog-footer"><el-button type="primary" @click="submitForm">确 定</el-button><el-button @click="open=false">取 消</el-button></div></el-dialog>
  </div>
</template>
<script>
import { listFollowup, getFollowup, addFollowup, updateFollowup, delFollowup } from '@/api/medical/followup'
import medicalTableHeight from '@/views/medical/mixins/tableHeight'
export default { name: 'MedicalFollowup', mixins: [medicalTableHeight], data() { return { loading: true, total: 0, followupList: [], open: false, title: '', queryParams: { pageNum: 1, pageSize: 10 }, form: {} } }, created() { this.getList() }, methods: { getList() { this.loading = true; listFollowup(this.queryParams).then(r => { this.followupList = r.rows; this.total = r.total; this.loading = false }) }, reset() { this.form = { followupType: '0', followupStatus: '0' } }, handleAdd() { this.reset(); this.title = '新增回访'; this.open = true }, handleUpdate(row) { getFollowup(row.followupId).then(r => { this.form = r.data; this.title = '修改回访'; this.open = true }) }, submitForm() { const req = this.form.followupId ? updateFollowup(this.form) : addFollowup(this.form); req.then(() => { this.$modal.msgSuccess('保存成功'); this.open = false; this.getList() }) }, handleDelete(row) { this.$modal.confirm('是否确认删除回访记录？').then(() => delFollowup(row.followupId)).then(() => { this.getList(); this.$modal.msgSuccess('删除成功') }).catch(() => {}) } } }
</script>
